import React from 'react'

function TermOfService() {
  return (
    <section className="ml-2 mb-10 border border-gray-400">
      <h1
        className="text-lg text-center font-bold"
        data-lang="terms-of-service-title"
      ></h1>
      <div className="justify-center h-72 overflow-scroll whitespace-nowrap">
        {/* This term of service section is generated by a script not included in this project yet. Please do not edit this section. */}
        <section>
          <p data-lang="chapter-0"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-1"></h2>
          <p data-lang="tos-1-1"></p>
          <p data-lang="tos-1-2"></p>
          <p data-lang="tos-1-3"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-2"></h2>
          <p data-lang="tos-2-1"></p>
          <p data-lang="tos-2-2"></p>
          <p data-lang="tos-2-3"></p>
          <p data-lang="tos-2-4"></p>
          <p data-lang="tos-2-5"></p>
          <p data-lang="tos-2-6"></p>
          <p data-lang="tos-2-7"></p>
          <p data-lang="tos-2-8"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-3"></h2>
          <p data-lang="tos-3-1"></p>
          <p data-lang="tos-3-2"></p>
          <p data-lang="tos-3-3"></p>
          <p data-lang="tos-3-4"></p>
          <p data-lang="tos-3-5"></p>
          <p data-lang="tos-3-6"></p>
          <p data-lang="tos-3-7"></p>
          <p data-lang="tos-3-8"></p>
          <p data-lang="tos-3-9"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-4"></h2>
          <p data-lang="tos-4-1"></p>
          <p data-lang="tos-4-2"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-5"></h2>
          <p data-lang="tos-5-1"></p>
          <p data-lang="tos-5-2"></p>
          <p data-lang="tos-5-3"></p>
          <p data-lang="tos-5-4"></p>
          <p data-lang="tos-5-5"></p>
          <p data-lang="tos-5-6"></p>
          <p data-lang="tos-5-7"></p>
          <p data-lang="tos-5-8"></p>
          <p data-lang="tos-5-9"></p>
          <p data-lang="tos-5-10"></p>
          <p data-lang="tos-5-11"></p>
          <p data-lang="tos-5-12"></p>
          <p data-lang="tos-5-13"></p>
          <p data-lang="tos-5-14"></p>
          <p data-lang="tos-5-15"></p>
          <p data-lang="tos-5-16"></p>
          <p data-lang="tos-5-17"></p>
          <p data-lang="tos-5-18"></p>
          <p data-lang="tos-5-19"></p>
          <p data-lang="tos-5-20"></p>
          <p data-lang="tos-5-21"></p>
          <p data-lang="tos-5-22"></p>
          <p data-lang="tos-5-23"></p>
          <p data-lang="tos-5-24"></p>
          <p data-lang="tos-5-25"></p>
          <p data-lang="tos-5-26"></p>
          <p data-lang="tos-5-27"></p>
          <p data-lang="tos-5-28"></p>
          <p data-lang="tos-5-29"></p>
          <p data-lang="tos-5-30"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-6"></h2>
          <p data-lang="tos-6-1"></p>
          <p data-lang="tos-6-2"></p>
          <p data-lang="tos-6-3"></p>
          <p data-lang="tos-6-4"></p>
          <p data-lang="tos-6-5"></p>
          <p data-lang="tos-6-6"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-7"></h2>
          <p data-lang="tos-7-1"></p>
          <p data-lang="tos-7-2"></p>
          <p data-lang="tos-7-3"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-8"></h2>
          <p data-lang="tos-8-1"></p>
          <p data-lang="tos-8-2"></p>
          <p data-lang="tos-8-3"></p>
          <p data-lang="tos-8-4"></p>
          <p data-lang="tos-8-5"></p>
          <p data-lang="tos-8-6"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-9"></h2>
          <p data-lang="tos-9-1"></p>
          <p data-lang="tos-9-2"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-10"></h2>
          <p data-lang="tos-10-1"></p>
          <p data-lang="tos-10-2"></p>
          <p data-lang="tos-10-3"></p>
          <p data-lang="tos-10-4"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-11"></h2>
          <p data-lang="tos-11-1"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-12"></h2>
          <p data-lang="tos-12-1"></p>
          <p data-lang="tos-12-2"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-13"></h2>
          <p data-lang="tos-13-1"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-14"></h2>
          <p data-lang="tos-14-1"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-15"></h2>
          <p data-lang="tos-15-1"></p>
          <p data-lang="tos-15-2"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-16"></h2>
          <p data-lang="tos-16-1"></p>
        </section>
        <section>
          <h2 data-lang="chapter-h-17"></h2>
          <p data-lang="tos-17-1"></p>
          <p data-lang="tos-17-2"></p>
        </section>
        <section>
          <p data-lang="tos-created-at"></p>
        </section>
      </div>
    </section>
  )
}

export default TermOfService
